apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/ai
  - ../base/adguard-home
  - ../base/invidious
  - ../base/jellyfin
  - ../base/kubernetes-mcp-server
  - ../base/misskey
  - ../base/grafana
  - ../base/openclaw
  - ../base/openshell
  - ../base/palworld
  - ../base/yattee-server
  - ../base/vaultwarden
  - ../base/wavelog
