apiVersion: v1
kind: Secret
metadata:
    name: epgstation-mariadb
    namespace: jellyfin
    labels:
        app.kubernetes.io/name: epgstation
        app.kubernetes.io/component: mariadb
        k8s.mariadb.com/watch: ""
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:9CMycBAvwfUm0KxuZgHdaOmOQdU6ow263xkp2WMyPaxROVut8ASIhxqToCaR6bac,iv:C61d2DaQt1BqIR5mBTRB660VxDOkMCuF2tnWxgJAIZM=,tag:fJs9QXiNGOllyBDQhw1YJQ==,type:str]
    root-password: ENC[AES256_GCM,data:C0LAhaMPeWza5HgLaHzfYcTyukIBdhrCMbQi3q3dwxxHqkgNVpshOTHEh18nN8Nv,iv:fPfIJSRKLG5Dx2dfU3ugUutZZ4NjaK6o9KNgq485p4M=,tag:hO9wGK57q6/fiJeSgQRTJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlY1hnRWJIWkR5NXpwNDRY
            eVNLeERHVXAzVDk5cUZzYjVtZ29hNUVnS3k4CnBoVUxDd1Y1bUwrMkt6NDBUMUIz
            YlVZUWZIUFlwT0tuZ3lYc2xiV296TGMKLS0tIHNBQkJJZk5LdVFXTEVBK0Y2eS9S
            bjNVclg1S0ZGZjJRTmI4NTdLSmNLTlEKz511cDQGrqSd8vXmmTsLE7sQ2gVrPS1Z
            wJnz35/dpzuCUOVxSLFykcXsTCW12Kkzn5147DSjXAwPVzu7tCNAwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T17:35:51Z"
    mac: ENC[AES256_GCM,data:7JWHgVlOk4JTFTgSsMEIBjSNg6vKEkW0HFfCh4zKKZtz3Zu2hw8SvPa01VZ+cmRx9PD0vC576QNMaVyanz4FoGsxeRhUeAEMhvDkyUQQ/3cR3VoOERXE3ZvakqWcaw7JB3P5+uwpU2rrKgEyZMQcpNuTp126bT7TFKl2+zWA59g=,iv:Soonk6N7PeQLc9bIZTBZOKX6voIT4WusxN37PJWUFgo=,tag:LMfQFKAE6ZcyWY2cORC/Nw==,type:str]
    version: 3.13.1
