apiVersion: v1
kind: Secret
metadata:
    name: rclone-music
    namespace: jellyfin
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:AW3gPG+Z,iv:q7vhOExnvmP7ljMV9mZFnR/EQTA6AiF8orzZWfS8fMs=,tag:LZKfRre6eaDa1tDYwBVXNA==,type:str]
    password: ENC[AES256_GCM,data:3YYaoWpCOgVVqHzinZ9H0i9O25OR0CpijTR77qZN/MfLkvT0YEfD5zddqz0=,iv:gcawLiPNzRSCe2JtnwXT1jCNW+nijsPxQ5vylsLqHss=,tag:mZ0qS1fGwA1tg1set6XePw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRzZveE5vb0Vhc3RFVjNK
            ZFVFM3F2NFNDZllESFdDYmdTM0tDZy9ka1RvClBMTUJXOXdQd0xMOXh5WFFxUENZ
            UXdCVE4rZXpnOXN6VUFxK1NjRG9xS0EKLS0tIE1Xd0ZFcnBwakVJQjdINUI4ZDFU
            ZkpUTVo5R0xUWHNVS3ViUVhUcWlOb2sKTfuO79ahmAZ58vvMy7CIXf/wCJn8NmtP
            LlENHULXA2+i59ggObsHjVa9zf2gSi43dLq4Sw9HumAjZbeiHd6kJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T12:18:12Z"
    mac: ENC[AES256_GCM,data:NskY/1/kz2/UOJ03030j/aw5QFCDEAMbbQ74PY86MyUjoWGIzXV/aLkdQ9jIrRaETm+A4YSiA6bfJeQOHx8HG/5+RBOW069lhBva/dxIuYsvv1slRphpDaR6E0UySNFaIFMjavhwitlQ4HhqyRESuSC4/RfTGK+s9PkYh6t59IM=,iv:w0Qok63aYPNrMfnJkEbawnj7bYHoq/QKMWaTMmni9bA=,tag:uss4B27SQNDlmsjl946qCA==,type:str]
    version: 3.13.1
