---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wavelog-config
  namespace: wavelog
  labels:
    app.kubernetes.io/name: wavelog
    app.kubernetes.io/component: config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-homelab
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wavelog-uploads
  namespace: wavelog
  labels:
    app.kubernetes.io/name: wavelog
    app.kubernetes.io/component: uploads
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-homelab
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wavelog-userdata
  namespace: wavelog
  labels:
    app.kubernetes.io/name: wavelog
    app.kubernetes.io/component: userdata
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-homelab
  resources:
    requests:
      storage: 2Gi
