# This example uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/d6114726d859df36ccaa32891c4963ae5717ef7f/nixos/.sops.yaml
# for a more complex example.
keys:
  - &admin_kentaro age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
  - &server_homelab age1he8k8ksks72wkc6aa93emst78c7xw9fd5n7s3zzx02rrctwtw3dsxsa92e
creation_rules:
  - path_regex: k8s/.*/secrets/[^/]+\.yaml$
    encrypted_regex: ^(data|stringData)$
    key_groups:
      - age:
          - *admin_kentaro
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_kentaro
          - *server_homelab
