apiVersion: v1
kind: Secret
metadata:
    name: grafana-cloud
    namespace: grafana
stringData:
    GRAFANA_CLOUD_METRICS_URL: ENC[AES256_GCM,data:gjz+1WaEe8D9HO7OMF/BR2ucIOn1+EVmOWCTg5bklUNPVoTu7Q7b8l+FeL08OFJgasB4JV2jnPvStIX2asjILJ8kUzNmRo2g,iv:PDJANpbG/dxqzdV6CIUaNnlUswF/JBZos2CRq69OWL8=,tag:yUU9YrQkOfqVUirZ41/IfQ==,type:str]
    GRAFANA_CLOUD_METRICS_USERNAME: ENC[AES256_GCM,data:Uc1xkNwnAQ==,iv:aINpSJENjzgeKlrBafNR7JM6Ny7k548j7ug4yQs7FS8=,tag:yrOzVBDB8XLAYBDDhMspjA==,type:str]
    GRAFANA_CLOUD_LOGS_URL: ENC[AES256_GCM,data:TK31nCZOR9JjThtlydY1gq27bQye2Zi1yu1F5Fk8Ueoz6K40MKMgvI71qz58fdZJOVE=,iv:MYqAgFpgzY2cmrbCVujSSjVpwlfrDH00UW+zInDW7xQ=,tag:xhvA4Z4BUFmvgVIW2Lzhrw==,type:str]
    GRAFANA_CLOUD_LOGS_USERNAME: ENC[AES256_GCM,data:97AWfTB7Mw==,iv:3Qjk4qdB417D4XLRrZTS1J41wXJmOqWFJe3U/LgT6Mo=,tag:pAPciwfRqs59SxbAxgSoHQ==,type:str]
    GRAFANA_CLOUD_API_TOKEN: ENC[AES256_GCM,data:pOLhSHf1GSbM48k11RU7RiCerkMtPS2cyZJgEBYv6dTGNz24bEQ+nfNRe+pI5p0NqMkwPt2Ktgp8FxI/YMzHQBx1i5TVukewFcEnvJBvK7b2a8zNyUeu46nWDijuhCy2FiGwXzg5+F8AoxSKi+EEuIHtUtC/uEdyDqRhvB0ZHB+pquv0wQF5oJrLMtmFvkVY71/wfBRp9k3cIFiQcsY+XHFJ5kHdD3k8,iv:Q+lUU+wcPewu6VPZaYpkrsrh7dzkLeimNYfNw2fojAY=,tag:qj6zKspV8Scy8mHxmExYPw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0K2VHMGZnQU9sRVhtNy9l
            L2NKM05zVHF6V25BOW1TdmRMbndZZDkvTW1NClRaZFFxMGxKallvakdDMktVb0hH
            MHdxY2NsVlEwOEYydVNHMmc3WWg5cE0KLS0tIFNxeG5paDhXb3ZES1R6NjhPMGtQ
            b1FiL0E1ekl4ZmtsYzRqbEJvMjRYd1UKP2Q/lNgvCXxw2H6COIHcRkZ42YBmkCTk
            MAhpGNk1iO2/w6fbufxWeSa5oCg8/H9mGCHG3tEDx80twn2iOH2luw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T08:22:57Z"
    mac: ENC[AES256_GCM,data:1II+583RX1YO3m3GYm6PKwReUIBjWsu3vGsSNOlu61cgR02jfq2fqv2qjaD6DN3LBKy3eaZW8sZtGB7mu7R9EwbBKOWQEsE0HAnbDrABJ3gVqoiqPlM0Vc2EG3tYijquE4isGMSJSnw7m8c6vm80J4/wrQ0xWpPl40HEbdmNWfM=,iv:4utOLmwYT7fX4hRBIqQtMjbBY5E0esWG6EvReV8K7MM=,tag:gFdTCmw4/7BZFEdkpPofmw==,type:str]
    version: 3.13.1
