apiVersion: v1
kind: Service
metadata:
  name: konomitv-traefik
  namespace: jellyfin
  labels:
    app.kubernetes.io/name: konomitv
    app.kubernetes.io/component: external-ingress
spec:
  type: ExternalName
  externalName: traefik.traefik.svc.cluster.local
  ports:
    - name: http
      port: 80
      protocol: TCP
