apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oh-my-ytdl
  namespace: jellyfin
  labels:
    app.kubernetes.io/name: oh-my-ytdl
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - oh-my-ytdl.internal.kentaro1043.com
      secretName: oh-my-ytdl-tls
  rules:
    - host: oh-my-ytdl.internal.kentaro1043.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: oh-my-ytdl
                port:
                  name: http
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oh-my-ytdl
  namespace: jellyfin
spec:
  secretName: oh-my-ytdl-tls
  commonName: oh-my-ytdl.internal.kentaro1043.com
  dnsNames:
    - oh-my-ytdl.internal.kentaro1043.com
  issuerRef:
    name: homelab-ca
    kind: ClusterIssuer
