apiVersion: v1
kind: Secret
metadata:
    name: wavelog-db-backup-s3
    namespace: wavelog
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:QiiL/RGdVamG2/ld9w8kWiPOljODfbyWscavGi+TAmXC4ZXuq7wqasrdZZh0uTOr9ksyiZUQm7LVFToO5g==,iv:GM2/cdh2gx/46ca4RlLRVp5kn/ASIY9stuLtCSyqWEw=,tag:RCZMihf+nDBj+3Ku8wvxow==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:2n/6ugea7d60iyT9hQa/Yi0ZpoSMuvntcY5hXxIlUmIh3MWAbTAFpA==,iv:BL5xTgcsrwtO92MSd+UyMGUXZv4iXswhic+KtIK1z48=,tag:dao522OWixw29FfjhPGqRg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsODdwdGhhMUFoZENURyt1
            cVlJZDVVSnBZaENUbEhoc2VhM2RnaVhXQWljCitMOGozWHRzQ1NVdDhScEtqRU9E
            Y1lBa2IxcGQ0d2k1K3d2U2I3WGcxL2sKLS0tIFNWWHVROFZPdkRZUGE5aEU0clhi
            dVZnRGd0c2ozWHlXbWk1RTNBc1NCa1UKsabj5Oh2JUn4GHwGpOwl7PHfVwLZVdiQ
            9DGZbMqIL+zWgLl9F7LOs6G5IxbRguf03bTGvOB+iEmqz1tfxmc7bw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T05:42:19Z"
    mac: ENC[AES256_GCM,data:GDEMAyb7eSlMEkqHRqOVDtmPfcNWFTMMYyfJBNSY2L/5KAUj9qPeMdwxO/rXvU8g4anTNTxL0V8JALo2hPISgmpyJy2mNJbjVHTv7wJEhi/zHNImLsivDnphU9oT982JNQ317gWlQ6pWM1XOWEm0oRCkaWLS4gVTj8oECUjookc=,iv:yQNPJWI8gAjH1XWGLTqBDq8+iVlP/ODOH7+ReomuzCY=,tag:99vCxqGKuuQF5xVbCaHHPg==,type:str]
    version: 3.13.1
