apiVersion: v1
kind: Secret
metadata:
    name: wavelog-db-backup-s3
    namespace: wavelog
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:bSYHKfznW9DBCAJ94RzAWPKPzKMsTZo/8OqWgBL38ae7irSxbUCH2+zeQD/8tgXpRiP22Ji64/w1gEUuCg==,iv:695cZ5/byIZdNBRWuenc0+8NunFcCmKR+X3TPwFuWPw=,tag:DBKTAx1awEkxNtepiUFBfQ==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:F+rP6bbyzl5MNWhHAX6ZR7pPk5QkAZdBEM2IfeUM760Wf3xujoVUJA==,iv:LanLB7UU/1R85duGqoXB87KbEzjkv3QSzyJZT4Xo8o0=,tag:b2v2RtuGttdlZmsKuBXybg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdWN3WlFGWFgwdW5DSDZJ
            MTlwck52UFhGNmh1Q05Md3BLVGRSUElURnh3CmhpTWYwK2lzMEorU1pyaC83b1pR
            RTA0ZHJmL0dNdVdMbXUvMzRTZVl2V2cKLS0tIGEzSm9qQ3NYK2o1b0FPQzRxRDg5
            Q2VYbkpqcVA2cnYrYUVCbTZHR0g1OFEKN9pwh5QH4qtxQgeSKfPVpXPfklhzX2fx
            2kq4B64IYE1EuCF76FEwwm+cKY9NSSlF9vgbOtJ2gnnDDqhPa+N2Yw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T18:18:01Z"
    mac: ENC[AES256_GCM,data:R8COMf6edKCR1SnqUaTjl41k9ZRCOkRZFzmFTXTforJNTXKDfCKwoWiK3DBV6SWbm52pPx6Bvlci3uR6YGM0pS6W7/w3G5O5y6oRwENak9SwMeMa3tlhAjM26wxKPI1CBujEvoM/MoKE+qEMyyIVuGVJgp8mcTpJCN04hFmOqmI=,iv:w1hpAJHNdcCyXLb+SK8haprP8nVU8QzAOBHAPZTFUMA=,tag:6jUEKvDnj0t5xOlgO3aFbw==,type:str]
    version: 3.13.1
