apiVersion: v1
kind: Secret
metadata:
    name: wavelog-mariadb
    namespace: wavelog
    labels:
        k8s.mariadb.com/watch: ""
stringData:
    password: ENC[AES256_GCM,data:Ven/vr9vLJKWPfJtOJffYwHy9hs=,iv:951JdoTf4+9tvSag/vH9OotaTks+jCv5EHv4mPJQY00=,tag:brrsNq0wzpHJdH3Yl0Io7A==,type:str]
    root-password: ENC[AES256_GCM,data:/Dz0jbE2sSe4cDvyu9wyfdOFfYU=,iv:cDS2Hy5p+Qvgr8QWZZClrFcogoTGFPjulOrEjaIC2Ps=,tag:gXKTbRgNWdFDW5hse3P+yw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1QWRIVU1oQ041Qmh0OXBR
            MU1UdnhVOFUyT01QUVEzY29vUVd5YnNXVnhvCmRKa0c3Y1BCNG1yeVdSRCt4OHZN
            dXhiMTB6RUdWa20yd1kvRkRqdi9DMjAKLS0tIG9Gd2wrWSs5MS8zU3RNOXdZR21a
            aS9mZUlZUTJ2Y2RQMG5FeEdqN1VqZDAKScSgM3Vep5TaJJ+3cFzcLEeRFHTYYLbH
            H9X33KUB9eSXTEsUjMXbLt3L4bJGqMaw482lV+KlahkYxUpqF/ofvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T18:14:17Z"
    mac: ENC[AES256_GCM,data:y0P/MZOEWEHgaloiPl+Qnqgt+U8GjPMkewB9uuGUBNhfvmRbuUk6g/9ws8SArLyl2/Gm3f6zljjPWZ4nK1Q4ALuZ0hLV8Tfu2Gauy5MRmFFSQAfXCcbtHCzXqgp2dp0Hh0tzWWqzoQi46AwGb7+anKvakMuTRxr3C10VWUDqIF4=,iv:1uzvWJZTyMKE6aQ6LkzFZ4dDFMUsbSH1acgd//Fy8vY=,tag:uKKaOsLJ5Pno/wZRlCxITA==,type:str]
    version: 3.13.1
