apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-credentials
    namespace: cloudflare-tunnel-ingress-controller
type: Opaque
stringData:
    account-id: ENC[AES256_GCM,data:LgsrUXDH1Gn0cZBA8E6jTtZ/VmzX+dE+RhzvvRze1vw=,iv:XD1ZnjdvRVOuGTUwCLG/N56n2K1dktdoNq0zTx0hYNw=,tag:PRfr1B90yzJ1Dxs7EKZnkQ==,type:str]
    api-token: ENC[AES256_GCM,data:bm39K3wavftG3svBBfQgRVQj+dcRufJCq+JmgYCcAP9Ddd5NZvsBBDdN7YVWujSenxBODaY=,iv:lH4OuyzCyL1Xt4pM1P6V96L0s5g4NLsoH1JE9qzn/vo=,tag:I37/Eb1qjca5Sa9sFBufYQ==,type:str]
    tunnel-name: ENC[AES256_GCM,data:1QeHSiB8Sw==,iv:JSRI1JzBCfAdzCad/dUQZicKPvbdEBbhPZhTq6XRX4Y=,tag:Z65NhbJJGNB4BcsmVq9sBA==,type:str]
sops:
    age:
        - recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdms4YVVLQWljM2tyK1gz
            VUVhSm43SXFDSmV6Unk5TGh6TW02UW5TWURVCllvSnd6cmJFWW8zU3VBSWU4ajQ4
            RDdHQzVTcUJEMjJLWFcybVVLOWFQdEEKLS0tIEh4aS9SSCtrb242cVFpNmpuRkda
            aGRLcHlxWVc3a1V2U2MzNmhpMG1EQnMKjhz3LyoJ8WEPDHaYYNWd8HaFUa35+oSJ
            B+WYK4yJGcQT1WmiL7DpnOJ9Jg9CQNuISOibzGNF7JsQ9MJa5ugvjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T17:17:52Z"
    mac: ENC[AES256_GCM,data:byT7PXTpQZnXI/w4/nBw5Zv8dhuIU6sBW35IY3e7HbrnEufReupW7dCLQPGZ6AK2ezLZIzaqxHr9eU8skJpW2ubZSxFTg4EW5oQoOQtJAUgMi+tvQdaSQZRPmntYh4IQmtgkvxaHxT5AE9rsOfK+85t4L8yB7yzoBw4tp25zBzI=,iv:k/URDEOeAh0hrRY74fKjCb3uE4ttS/uURPxWspxzzfA=,tag:Yty7UGvqwDzWkpb3cv2H7g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
