apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-credentials
type: Opaque
stringData:
    account-id: ENC[AES256_GCM,data:Zc5cqE5NDKewaXrLllpO1QeN+QB1eYMjU7sxLFtZfko=,iv:WihMBpntXQfzQZdNLFX6WWwzJQy/apRpcbnzYiapHNc=,tag:pjK1I3w1Oy/ST162xbBFZA==,type:str]
    api-token: ENC[AES256_GCM,data:S7SYMtb45YMZ01+BE4CMlvZjRHR8e4vY1Gr5h1p6F3ivd7wUC9qkG0wgYnZF8N3yDjWdiL8=,iv:359ouvILCPElvwxXweJXLYszG/FrORhC1DrUj/naOME=,tag:WiLG9DPTw5ZGzqbxwCWzvw==,type:str]
    tunnel-name: ENC[AES256_GCM,data:3ZfqohgevQ==,iv:KN6iNka3CWiaV9bvUWhKQFU/m3Jl3WwHR3BPCcSkHUA=,tag:r/F31H0Md2zSthXXFxKU4Q==,type:str]
sops:
    age:
        - recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTEhxejFUKzFXMmNoWEJx
            aUtNNTRpT2ZFWU4xWjhYUm1hUU80aHV2Yms0CmhTV3NHd2dGRjlORVNZcVFLSGhr
            K0xVRXl6alpEUjk3NUo4SnJBTnlsVTgKLS0tIGdZZmtXZHI0Wmo4cWZ4czJVOHlG
            aTl4RWRYQk5iYSt6Y1RoMlZ4OHljRkUKe03w83leMLNEW+CyP298fii3N+8pSP1o
            nA3HiN5H8quAGNb/s3+DsimKgJwR1Oz84XAQGl6zvxiMYKmD4XqUqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T17:03:51Z"
    mac: ENC[AES256_GCM,data:WALwYEk4HR7mfkhswaFHQdX1YOpQEXg3GXP6lMIDwORyjxq7j6qIiOsKbgJo+aFrJmw2J3II0QbQMLeam9dHnjxNZ9a23e2t8N3JFko110jJ98a8vAjHunGoQMdS9PBUtACgJyvG8Z/j2U26VV8RDyNIr8cj0fOvbVQd94LKtIo=,iv:VHAAIm/LngKcsXZHl8wYzCZ3u8T1ALGDRBvS5PYsLyQ=,tag:a46bE69hnxtStLv99oz95Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
