apiVersion: v1
kind: Secret
metadata:
    name: openclaw-grafana-cloud-mcp
    namespace: openclaw
type: Opaque
stringData:
    GRAFANA_SERVICE_ACCOUNT_TOKEN: ENC[AES256_GCM,data:H3GBkRcAvNGWWxuKqQKskQo/qawz3wqwRJm1lzymwCKQ8H7CXGaIvdESUk+o+A==,iv:Qh+Z7pBtwYAuSuKnUGB+6ztV3XmgSxjhemwQcAMYrQI=,tag:WVO4yzMkb1QlhQ92cacGtw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidGNPRGtrK2luVWlSVFZn
            RERLQktPam5sd2ZqQjBkSXVsZ2x5aWoxZ3hjCkRwN0wxR0MzMDZXTXpxcWxKYVRk
            WGQ1Q3cyTmxqMTFpTEVVL092N1VsbjgKLS0tIHBwL2xWQStITU42TFZEZEppNzk0
            UnN2Z2Ruc3l5UzVaSTRqbllGV3BQS00K3FMWCXi/x755hRBVP9ctgshbVyP6azS2
            J0TPU+eI2P9bfBkLTcdpJ27UMMN+GPE+yU62snWQpCZ8ZrosC0AC8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T12:49:08Z"
    mac: ENC[AES256_GCM,data:cJHXS0NrHlMgPlxvYbBtYdzdZyqHx3qx/Dv15czEQCISc8bD/S4Uskj0s7OEJj6/Go9qVG2RH3lgD7+3o0OedA/ShRAG3oEO6ABJcnWWKwWZDB/KUiAXzf/WEuahrVKyIqSOESjGRp2v/n1HS6UZiKhPNWhmrytvp1f2uk8tJeE=,iv:pd7L06jNHoCqbgLUn18E7v6abFJ91537QrUODyEiXXo=,tag:OGLSY+X77UNhmYUeSFaxhA==,type:str]
    version: 3.13.1
