apiVersion: v1
kind: Secret
metadata:
    name: openclaw-grafana-cloud-mcp
    namespace: openclaw
type: Opaque
stringData:
    GRAFANA_URL: ENC[AES256_GCM,data:q8MjbzNX5lqp4WANbyG61VjubrWGRkOiuP6Q,iv:VxANkEq+aNo9Hk++L1SdDRY5SyyOGzyq8lppnXfnNfI=,tag:K+s7wLm7fhTrTzr8mNjziw==,type:str]
    GRAFANA_SERVICE_ACCOUNT_TOKEN: ENC[AES256_GCM,data:hNQUqZp2xkdMwA==,iv:YMm1X4NLYXW04aIwYcCs6IuFQY5fxvkvmDxelUKqG1A=,tag:5gbh55sS7kOX+GMNZeBsrQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKejdrcUdsbmwrTHZlQlhD
            VFo3WXdyVC8yeVc1UTN6SHZUVCt1YmhxdVdNClJPajdEclZwZ3k0RDBRV0JQZkkz
            VC9pODBsYVZ6RTAzVm42RnVJQUIvZncKLS0tIFEweFpwOGpVRUF0VnNVYTBnVlJ3
            UjRpWEMyMzYwODI3dkV3TVJ0ZVNacGsKagMsH6cSIcX4QRwBOmsTZw692Ju+PlyJ
            jy34hHEtyRyWC3EjUQ9nI1YBQtB3WQQupSA57cluNuoHJb6fxGdRsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T12:29:55Z"
    mac: ENC[AES256_GCM,data:oR5uiQEsqgC8opTrJ4nSuJlmSpxImUQQcdVKYdopuRkPw4p2WqgbtsmeSMtJakThlbrEmruYcg7BKOxRJVCrypb80GQJdK9tEgWT9IHBezOQXZrQfMWYxsT8esSAw8hwfGqynGY38/4Qtp2mERGIf+yUOOt1lXtoJHEbR+IHOk8=,iv:QujPFp157R4bAdiGZvaWs9dbLa0ddnQHrjRatttoi1Q=,tag:/8pnrHbocPQGyzUwsVOU2A==,type:str]
    version: 3.13.1
