apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secrets
    namespace: openclaw
type: Opaque
stringData:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:UYy7PwH1R8PV+FLUZ1PiP+/FtyQ7z+7aMVzdR93opyWJFK9El5KUCKRYX26DKnGhv7obdvKTun1g3kx2ogU1pQ==,iv:Bm4SnkOKZ2n44vuh/uKBLl20ymXOqUw67kHwowCZheQ=,tag:Jtro+5C2Pgb2xEQ2uCZojQ==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:fBokmCM61VXXnrOfbH+oIU0Ur2WseQ6Ob+HU+3NPTNkt821SgnsURA7iijNsQlwBZT2SKgU=,iv:447q0gWIgAzE2OK5jifAvRrHKNR0KMrq1HWzH1Qxo7U=,tag:D45/JSxhnKFEcwa5yFFW7Q==,type:str]
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:uugUwsYXs3N1XDaVMJlHyUIbJC9qXFor5nva5h3dVGOdsERIilA6YXs/GVS91PKc2nL/OEyd8MReoBpNQ3vrX+wXX3mHV+8+,iv:cI/ZZciA3qQfX1x5Sa9QEvJ0EqWWEEO0MWJavAlti0U=,tag:MedLyCNUO2p+QBi/8exNBQ==,type:str]
sops:
    age:
        - recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWHp4M2FoZ0FhdnhyYXpN
            Qlk5dHZrcEQwZFN0TTgxRkNITU9XUWJyRUdnCmw5ZWx3eTlQR05QUEwzb2RJaW1q
            Q2xyWTIrSW83KzBYTzdTcmxTbDF4bWcKLS0tIEdJdEdibUhnYTJVVHVUdEF6cVdG
            ai9pUk9kZ0h6YVZKbmZTYnd0S3BzZkkKGMpz4GaK5s3y4uKInKwp5u7ybvwNZke8
            bIwqkKfW2iGHNx3aG1DUoBSNcIKLjGdLM9BJAzw1Y+4yBH9KiiQrdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T18:57:40Z"
    mac: ENC[AES256_GCM,data:+BkMjkubrNWm8VWFfkMYZUMteVob5uuhVeAIqyQNAJAFQWRh5HMW0mnriBXKaZQPa2nOgMqNyE+8HZZcrl92GgfVm1grPqiJmEaz2A/vBsjbInI2xxh8FMJG402rJACcxPxoGH3fFADve7tVjEO8VrRp61ptAICDiodh+ISb3M4=,iv:pCDuYd8cyHKG4GYpuyE9WnVr8YF84KQtJM+K1tS8H+Y=,tag:kdsGGP/UyHH+Vcw7k4YoXw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
