apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secrets
    namespace: openclaw
type: Opaque
stringData:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:6o56MJjbsfuwXQaX4WN2C85d5syItIgi9ICRNNMm1FQTv6VauSsmtmk3/8AG2KxQ0OHhghgZjUymWKmfxgv9Cg==,iv:NJAN3nF+xNEPxkw2CPTlXk3ofoSyHncqWfnt8e/62L8=,tag:1KV3ktkCRcfswl+OhE9LwQ==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:RB1Z0SSZ66FFMGggiMZTRSvgWFwQ0vSxGTlCYgfcZghmq0YX3fa25PD/gHSgagEr5+up3PQ=,iv:XkkWcFSU3F5eKduZiQo70wLkF56xcNllC4eJahjbSSM=,tag:ypi1UFU5AQOd7D4O52lukQ==,type:str]
sops:
    age:
        - recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOR2w1V1JWMGwzZ1dHbVZk
            WlpsR2tuQVREaURkd29vYmRwYzhEeGhwR0JzCnhXOVpVVjIvR0ZxQTFGYldGcjJY
            VFdkclFqbUtNMGpkd2h5bUdQUlR6WVkKLS0tIGcwYnVaeFVxZWFUYytNUnZuN0ox
            ZlYyVURSdmpWSHNmZ2RVUEU5QllTS3cKxXIIijTpVf+eQ/YGByWZC8iV9DxtidFJ
            gwb1c0d5CIpwSNugvhjHx1j6AYX0UitqEj+tYKjBM3g/EI2xOIphcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T17:56:36Z"
    mac: ENC[AES256_GCM,data:+BCxVxD5PR4l5d1bobJDvGXuFIgivzE2OdXOdw/1y4uFMe+D6EybnSt13H/qJsVgoaQ+bC3h1y3oGtjDVR/mdnm4JdviQ3BSOMeXq2iIK3/HaQBDG6jNek5P/TT68J+KJLs66ELoaPe3KOGOtdohUQzslfYNoCCzK9JA0CrRgEs=,iv:Od/aT3LGm8gJTeB0MLze9aWbdnUILIjQaTKhaZAkEo8=,tag:xBOwAs7CsnAoqKpFL6G1aQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
