apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-postgres-backup-s3-credentials
    namespace: vaultwarden
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:zyrxrJ7J5ZIYhmL+5znspmaO5zU0MPb2ULbCWyGUFr/D9N13Sjksm+kD9ELFKnw+/rUtXowSK2evVM/WTQ==,iv:cE10TsVXJ8ozPUisxNGxaP+bOxGDJPYVH6zhVMVzaf4=,tag:nHMA/5JV78lrymWl/VA59A==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:ldQv8EHbTkO41HqvZTwPE/Pdhtdoi7xBU56Z3Kut72OUghpaDdD6ug==,iv:HIIo4kc//rxjReFGJA6IaTlebGEu+FQXZW39K6u4YPA=,tag:Ak0lSY+REUJwnDNCUIwlKg==,type:str]
sops:
    age:
        - recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUTVQczB1MGpnYzl0OU10
            dS9MZERJZTI2cERWWXRWNm85RkpaNVMyc2hBCjZwT2o2NlE2NVRtcjc2QTVUbjky
            ZGZvRkFhY2ZwV1hNcDhvSzZFUnBLYTAKLS0tIEsxMkZDUnVvRmxKSTh0WjRRM3B5
            UUhSQWFIQUs5N0lCSmw1cU1tSDU3Q3MKRmCXZqEEWR62V2vw8iFmh1RAY6gEjSoj
            voH/IiuSnvvDTsqF0psWSr3mI8f71IiPp2arN8t8ZP+69TxvyZf0uQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T09:52:47Z"
    mac: ENC[AES256_GCM,data:DFW7cwLxjCM83cRetyth6exl6mZ243OyAIWufJUUHH4G85ClcbgHb0bMrv+nWr+YHdhzUQS6nV3hemQehdtb7YuJf+WuFCKLxH9Ugf1iqtDOH/CDNzFiE/0B/FANkSlBUWSgli3ojf51qFtwqNjghL3kGy66sd+jzY8fYkJ2UGc=,iv:gNSi5z2yAOw1UNaQ4xgagO7fv/nMZItVh7SOKVu0okY=,tag:98BNfoAcTyZaH7oh1dSMqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
