apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-postgres-backup-s3-credentials
    namespace: vaultwarden
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:/ePL7V7PRVHetyB9+lysbGLIi0FY6liC/qVj87NfLf+1aFrju5340F2h1rsag6feR0JasEH8pQlpiuGixQ==,iv:1P/EKdwOIsrlmR3IXFZejw94y8gSQ45qaIbkxLIQT6k=,tag:1akS7/cSU0SH6E127DwJGA==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:5QFWqRO7c7IC85Z0kzvVbebz8p2MkAim9Stj1ec7fQR0f2lD0KzxBA==,iv:/Hn4WMbXKt3dUyOwCvRTpJhlRdjTMBEoYUC28EFqv4M=,tag:Bu+o2H/CHnxlPFlIs5lsJg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArM3p5WFRBQ3FndnUzS0FF
            RkFjd0pGeFpPdVJ5NU1vT0dSUDRJN3NMQlE0CmZOMDhPWTcyalNZcUpyYjhxTzZG
            SzRaMFdpQ2l4MWJIV0krcFVxRXY5ajQKLS0tIEc1VmdLRWd6Sm9zNzBLOHRzbm0r
            N21UcGpJWnNoTHQyZDArMXQrSGNKMU0KfJNxPE2ioAzZ2EkFzRrVP2TquPwzLFt5
            6Tg3HAlzjL65XbFSusgS6G8hEvt8i0OLta6lROVqxFA6CI8WVNpq7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T05:41:38Z"
    mac: ENC[AES256_GCM,data:l0/MvcUN3B0AGLTJPj+jqXCZ1++pK+EntvYRabhdYvq4pufj5BwAcIk0Za8mwH7OP9pq0+WSzFNnuGN/WUpK1W1PjBzMJUAgsOV2mrGa7lfrj8+l4K/zR7sxKn9CigdHBFRJMdS1+8f2d1tadjCJmJ7zS8o+AqohgBVPdp77xm8=,iv:cAirqe1XtxYEA+ibxNU5kb2hnccSziyjQkIq5GeeUr0=,tag:qXZ0fGaJAW7ZqnWi18fUeA==,type:str]
    version: 3.13.1
