apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: codex
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:l3HgcKnMlHteiACBFdOYWo9zvWrxnTrIk3o7EooWILKPshs2yCLry5OQZbZLd31QMXd4WKOR9Kw4YAup97J/jY7LhTiVhqwn+uckwkBFGamsLC8TMBohjfsEz0vX6jDrKJX17VtLAMpkzjQ6FMxFOAb3SKSdD/9u7LUBozxQstq4UV1dbQ==,iv:MR+Km5W325mf7/OJCx/403wpSn1RLN9ZN3eGjDW93t0=,tag:4MHzpRiByIUHPJJdlKd3NA==,type:str]
sops:
    age:
        - recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVlBDa2tnQkFVTHNNY1Yv
            QXIyUit2VVY0NzRac2F6OEtoM2M3TUhlSVc4CkNSdTlmVmJ4aW40dmtqMVdTdzYw
            NVkxWmFjOHFuVkRvMnF0RER5SXVlNXMKLS0tIE1uRlJBTVNtNW9iekt2TU16MEhJ
            b2o4cVF1ZmFGNWdMV3F1S01Ta2RYNGMK8fYwiSt7w4I/AP+lYtjxkRcC2CSQgMRd
            RLAmnIgbFcaDNyWoqnCjpuu9myoPk6MhU6TLl6csr9f5REZ8e4ftig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T16:03:19Z"
    mac: ENC[AES256_GCM,data:hZyq8wY0YZUovFjbIvsX8StTYk3Q/3oPB2r0mKIBraUwUsx8ft0Vb4Zlx11v8Y7UWxtVvQ4/M/jyMBZ830sYZIMrZ/hCZGHUc2Hd01jxHUlrlNhQ5riHSDJ0U0IjQRObl8tFAMAat/B1lt/zs4cMu9asp7dRRSvnecD4UVylvIs=,iv:7BtIF+UaZDNvOm4B5pnvf3sVoSI/W7+Nccm251u8ZD8=,tag:fSp1KaEfPBVcYyOQ9Gp81Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
