apiVersion: v1
data:
    CODEX_MCP_GRAFANA_TRAP_AUTHORIZATION: ENC[AES256_GCM,data:WZ3JWxUL5Kz3uKlqr+f/SlvBQB/wa7iXZijl3pBDs3JRmzvl9ad5QVsOAtzWHtg1RV4vzrWHkhaHYHMS8dHfHrugom0B7plxa0fc2tBfu9oLbn8l,iv:SvV8gqGhRa0LHFpfir1S0diyynzHw71Lu96j2enPtGE=,tag:ZBtcHReFftoazp2aSmDMCQ==,type:str]
    GRAFANA_SERVICE_ACCOUNT_TOKEN: ENC[AES256_GCM,data:zGnGMfsIsE6FqGL6UO17nvSqBS7YrjvwLdqE3HLtuUt24N+0Rw2ZW5kAUJ3FilcaeWmM5WavYD0dJcx0ipv3bA==,iv:Xgtk2WHzIrGnXG9dAP1rPeavf9v9XQws/WCUlS/hUy0=,tag:pP8JmysKiubFf7TpSHRNbA==,type:str]
kind: Secret
metadata:
    name: codex-mcp-credentials
    namespace: codex
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTTZwVzBOeFFxeDNBSEhO
            MWhkT24xNjJJL0VVeDFVNlhUU01jVkdydlRBCnF6emw5am5FS3BlbHVOcWZtVS9h
            SFI3UDd2SndSemxyaEoxNHRGV1RhTW8KLS0tIEtvZ2xKc1U3MVorOUF2anR2bkpH
            bDJkVVhvWlBVWTFuOTFXRWRvZVlJbVkKqzjKerHUxebF8NoAgrvZWP3xPfU2rAC4
            tttZtSr5M9KYAw3RFGWpv56QnifTGHcQV4asTEBfkYMIQEnhfZt0jQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T13:12:22Z"
    mac: ENC[AES256_GCM,data:wAFC7YrXvQhB9G2SoPaVceqbOaS3wm+NhP3O9+wUr7vo8Ur2Wuo0olPhbmd4B/ZaaKLgxWFnR0k7l/HQbUs5pSzgVzpTfXcTXlXWAMa0OWtjgaXPfRw61B1OFuGLkR73zrW5mQV81HogvKb2iK80RBAAHB82r5rTpJRNenPw6us=,iv:aX+FoNdtvXGMpqEbQNuO4AjiGeaUbu/NcZpwHMszKKQ=,tag:VLK28Mg2oeStQwoSa9fB3w==,type:str]
    version: 3.13.1
