apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: epgstation-db
  namespace: jellyfin
  labels:
    app.kubernetes.io/name: epgstation
    app.kubernetes.io/component: mariadb
spec:
  image: docker.io/library/mariadb:11.4.13 # {"$imagepolicy": "jellyfin:epgstation-mariadb"}
  imagePullPolicy: IfNotPresent
  replicas: 1
  port: 3306
  rootPasswordSecretKeyRef:
    name: epgstation-mariadb
    key: root-password
  username: epgstation
  passwordSecretKeyRef:
    name: epgstation-mariadb
    key: password
  database: epgstation
  storage:
    size: 2Gi
    storageClassName: nfs-homelab
  service:
    type: ClusterIP
  enableServiceLinks: false
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi
