apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tv-recordings
  namespace: jellyfin
  labels:
    app.kubernetes.io/name: epgstation
    app.kubernetes.io/component: recordings
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-homelab
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: epgstation-data
  namespace: jellyfin
  labels:
    app.kubernetes.io/name: epgstation
    app.kubernetes.io/component: data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-homelab
  resources:
    requests:
      storage: 5Gi
