apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: valkey
  namespace: misskey
spec:
  interval: 24h
  url: https://valkey.io/valkey-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: misskey-valkey
  namespace: misskey
spec:
  interval: 12h
  chart:
    spec:
      chart: valkey
      sourceRef:
        kind: HelmRepository
        name: valkey
        namespace: misskey
  values:
    resources:
      limits:
        cpu: "100m"
        memory: 128Mi
      requests:
        cpu: "50m"
        memory: 64Mi
    dataStorage:
      enabled: true
      requestedSize: 1Gi
      storageClass: nfs-homelab
