apiVersion: v1
kind: Secret
metadata:
    name: litellm-secrets
    namespace: litellm
type: Opaque
stringData:
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:5D50KOiT5cfkMRxdihKgoqyl7BasyII8bSmbHKQVHMSG4bhk8t5B8g==,iv:n/dMmsFCu9EegxY6aHiLTv9K0LX0KNz5pbAcjCZFYjA=,tag:x3Egc39aBfgpNC5XUShgKQ==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:2Mx9n21/icf9Neo/cLjgdppeTr9SFmRbkcKJpQmsqCFAAzaONZlNU8e2HjoiXH49oEi8VTY=,iv:JtkqZPI9bUi68lGRhISOCv6vQL2N560cV1gBWGaB+/o=,tag:gdNsfgvwdCpyo4nLhe1U8g==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:UqNhXUxQv3obJOBVLpeh7f5PEp8dyoOqYeeBoAR/TlruIf8XEvctVA3odPOrGdHBtw/kAQcnnCoVs9K1KeNJ5pbtCvpDZNEdgQ==,iv:G/eLRefd7K34xYn6DWUbOkTbMuH9KMfqTAVZ/V225GE=,tag:mYGNkvkSVYSVNWi5G9S/hg==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:s15fbRG/aUdJuIDYSCEMuCP0QPuZonYHjLHrvSsHsxATs4uso1GtHh0V9Jf59aDKGyVFEDZql8fl6+SDrR8aCg==,iv:/M3+IfGUY/dGut+2XJ0tDpyJVqgUwtWaRMw4uk9/weA=,tag:CRpBBOWOCoilNmC9Mm26yw==,type:str]
    UI_PASSWORD: ENC[AES256_GCM,data:Ty72wW/jaOqQblV9AAsQ0r4WMDA=,iv:m3VcBbEfpbAPhSs6cSYyHADCwa2A+KpUsq20xJSRR64=,tag:M/iVsjoSoFH1FMTh9rcuKQ==,type:str]
    GROQ_API_KEY: ENC[AES256_GCM,data:Pj6za0MZdTKNyb9sM8eKzekFbZCvxNpRTrnGWMqjXLqc7ycQN9nGRkC3eSK8f2dLFKBV9fLdkdg=,iv:Y08GR8WRaxr289iqO0eeF+WOx89eyN1FW+o2SmPfqo8=,tag:5EwGztlAoXT/kob/E+xwQg==,type:str]
    OLLAMA_API_KEY: ENC[AES256_GCM,data:5ukwcp4jCBZIO3K6f2lgVKVMKiIAa/bxvOQ2ewYxGdWMbwQthGbs49R6LoW6LO5eRAlvw00y2QOg,iv:56LBxAspdVUmgof7bLF1+BHmBI6Z8V71UxwDO3VgZwg=,tag:g5MCaPk88gNN8Rf/4M+s/Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKaUpkQkJsRU9KaW1HRDA0
            cCtMVUl2STVCSVAzZ2NibE5JbUVBa2VIa0UwCi83ZEJSek5nbW9rajFiZVNQN0cz
            bTJiNlY3dXNQU3hWS01rd3ZqQUwvWmsKLS0tIHZXUEgwMk0yMko3ajNsTXRpN0xw
            UEVQUDRzSUI3ZVRwenNDaGR1Yk55c0UKwUQy1ma39gBfzzuU1J9oQbUVlsQGQR0M
            UeBhtlXAl/EQDevqLzmbJlg32DnDGNcTUmy5GwUge5/4oi/EXfmySw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T14:55:55Z"
    mac: ENC[AES256_GCM,data:mV7v7rXb6w94EvDM2wZN1EqEJWoy9JeY4G7VwoMAKCKx2txWgkOCDaR8uDrtHGwVXu3Ha2QLQ/zoqSvqIWcm9RjOSYyr87gn/xOB9jmHvSPmmP2PJunHtPMvVbbWR08kqvQs1WDWYjawgGrRVXycO81UerWBnqjIb9+QgaQa2G0=,iv:/0l2KiTQtMavnTRLNDuZNpeIDjTDv7kZ6ZtATKiU8OM=,tag:1S1v1fk4pVoJutMszOfmpw==,type:str]
    version: 3.13.3
