apiVersion: v1
kind: Secret
metadata:
    name: litellm-secrets
    namespace: litellm
type: Opaque
stringData:
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:ZHhtA/WlNRb0nj7yGzb2eAxFVgc369rDNJXdiBUU6kVkbVigdry6cA==,iv:ksxyCHwm7w8abvKvT/K474uoX0kl/2w0J/ZVf/BlYJw=,tag:ZHTyLA2lsmGqLWDzUOls6w==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:/TwbKXzIzOh4Lh7bZdE5zEhGIlJxHx8xGSC87YJh7Vr9+Clld32Ksk5zrwKIq6Q+JMHHn+k=,iv:NS0X+vYz079lzYixe+mHkGsYQySGk3wzbXZEWLJY8Jc=,tag:seclsBq39WQWcWHI12sxFg==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:6NpwR7Bg0zT097knGwKwdb+Z76s3jPI65AwJdL68G84BUpey/EILt8/C2k1jukmNOscFEEyCIVoTrjGgc+C0Xzd/ts4QxIFabg==,iv:1aDrHuuAMi4/+NFDlsMDuBPlmZsjS0pYQDKU/Etbkn0=,tag:pX5lZFcwwT/fJ8UABcVglg==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:4kczBq0NE7qkILcu1H70HuhCNAOESLtGHC4wqAYby9LSz9mUPhzamItRTNlLNS5FTy8U7V/oBQbMBtuuJIj4iw==,iv:mgN2VqwGB6QP1tZsRG5Rylha0h4N8BRZVwGCSk0h1Bk=,tag:AsnxEZOrZbkPvCRVV7KGWA==,type:str]
    UI_PASSWORD: ENC[AES256_GCM,data:lbV6izto/2L4TCqjXfdSLw7e59w=,iv:WVeMkWryO+ebixUFEy96lmxUlcV5ETSmGuIDyV9t75c=,tag:K0CajYOKvhpdgElyN7W+Yg==,type:str]
    GROQ_API_KEY: ENC[AES256_GCM,data:O/AeU+iUW9o7zHid2Ad/GipEtMJbyxG97NtCYxXEt+80CICyLHL5Rv8V7KalePttrAV3OTWGK3E=,iv:dgFUCSTOhYVjdNIetx2y/77BPDcLFexO2kDDoa+GD50=,tag:0pUWloy4VvVxGWnURO/xPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkYU4rdmMzaEhWbTdmcmdj
            dGlvT0lzOWVqRzB1SmNNd0xZcHRNem9pTTNNCkNYQ0ZOa0toa3Mwck02T05Ec05B
            WjZwcHNUejhYanEzNkovc3pBUEF2Vk0KLS0tIENMZkVVYVl1blZpME1uMGhDTmJ3
            ZUJxek1QZEs5dnBPanhkOTJWTnhIajgKhyu1foIYfUVSSArcoNphqehtEWmcNso5
            Y4U+TKNH4mqc5rlyda61TigrBUPYVBVnY5gyqVBcPodkuuqsMTqNZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T14:40:19Z"
    mac: ENC[AES256_GCM,data:8LWvaEsxVGimHyLbFQE4gQWIFnj09BUiTzvoO5ltEiGg+wzXzYpaxkFf4PpJe3XA7Ko1I55PuWTfoslk0tdS/E7eZn9PiOg8VHqeaiUne+HWr0d9uxv1qpK5E0D58K3olpAfudA5SJPeeqpvoOet6dtyahhu6C3N8o7EwCumxfc=,iv:KwCm0UF+RZ1MV006/dq6yYqaN/NyEsfO4IVW2eUD46g=,tag:Pbj8B+PCCW77O5jMkXTmLw==,type:str]
    version: 3.13.3
