apiVersion: v1
kind: Secret
metadata:
    name: litellm-secrets
    namespace: litellm
type: Opaque
stringData:
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:M8NDCXNcWO6stZzOP6JjV1EJ4lDxWc1FRBY4gqx7X0Z/dwRSwcjkpA==,iv:4R1nCPwQIRnRi8i96w28qF4Hpn6ROsDlqxlQVVmz6J4=,tag:kOX/+J1/UlhSfoV+E9Q2Iw==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:aJTj4i8PEFLh/2ux/OMxWIDrdINitR774D1V25GRCudUd6GM0jkvitWiekfZ5DpKYHvXi/M=,iv:obg9b37oedujAVD44Ww5XMHkoFWUV5gvOOAICshUKq8=,tag:dFIxLlEFFQJViDmdYw05SA==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:LBsP2TOs0AmTBtCrIVwH1hVg6EuO1kLCwZsoCdIEfNwrxqnsr8+WSgjmHj/vuDcdaLHi5feGGQtZufd58/ACv90EjCFIvZ5I8Q==,iv:s1UZ2dbWFZS1AKt6NafP3P7KonKIcBLBtbgbUJnm9ds=,tag:gfwy7Bh58QoJ9lEUn57log==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:R6w3Uw6mANVJsnzAbnfV79FP8MrEvdOmjALLY7IRHNe3qzh4hugt2A04cxENUxGB03tZoCXEC+7s0R43QI0SMg==,iv:p1J0Pd8tx1dSGixLFU/lHizUEQaOsKFSZOde7S/lJBc=,tag:bJDb4egKe3m9zidZ1pHdyw==,type:str]
    UI_PASSWORD: ENC[AES256_GCM,data:bFOyOaox8HA9SRT4xRbu7iT0010=,iv:1/FL/rW4OHPrlj0g551M0TXAozVLnsYeRwdkv282Vwo=,tag:g/p2l4r8NqPNGHAuSUYXqg==,type:str]
    GROQ_API_KEY: ENC[AES256_GCM,data:bABJm0fbKu8Z6raDeGQiVPxXURELIEShK23Vk3CsMbLobGcokOAgJ80id6e5NdR55VylJ0sXJK4=,iv:CUTCFAV4hb07UtuGa9WVHW11uwNWTQTi3Su3abYfPVw=,tag:8vkyOlONl4AMHpduzbO7UA==,type:str]
    OLLAMA_API_KEY: ENC[AES256_GCM,data:MvwE/srxLEBHS5qCwLVbAIWusIWMNYaIszKvyhhW6y/qs2fQEkBC6oeg9UE9e8zsUV86n39aC4sv,iv:7FMKRAuQOQNh0exC/xksxpFXh+O1Cpg8IKJSdj7s1DM=,tag:SFcxRMLbToAxwzElZISOPA==,type:str]
    COHERE_API_KEY: ENC[AES256_GCM,data:UGbLR/BRSR3e9auXQBdkeTfYjQ3xt2laUSCplrgx3fku/v0aqaYndg==,iv:ENpf6ORzcolTUEHKH7yQeoQN2gKbZUPiWzHnmBFNnZU=,tag:mGNxq3lAboztTh9XfIQo3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbTJ4Z09Kb3grNU1pUVZS
            U0ZaRTJzUC91bGJDd3lqYS9OMGlrN0pUNkVnCkppcWd2K3oxZTEvUk9jWnpsUkFz
            bmtkRk9HYUxXYUJjUHB2WnZnU2QwQ2sKLS0tIDF6azVaSFN0SkRUWlNGblRzOWY0
            VjJ4VUNsR3hDNkZMQ053OGlUZDAzRGcK58budE7XuOrDfteqNuSa4SwTjTwO/NS/
            34t0n7FF1B5XvhAGU7bU3mOXtBeYbjhYsaMXj94IKxH9ifEqKbBaXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T15:17:41Z"
    mac: ENC[AES256_GCM,data:y+mSo+sF5PwhB/beMiQ5SnS/Vn6YEgT7JUaBhyWyPv97RL/NJPI7mnRUK6LMhCJRbnupAsjnRsu+89+HpgTprp44MWTskpOSne6D07ckPAApXAkXpHyKxXXwvPPuUn2wgnGYz/noB8f+fYM9v0PKETGIXdkGTYgJIk5tg9rxnWo=,iv:YRcQW9Q6zf0Cts2Eruwlx1CDAUPxXrsxSRjsr63igaw=,tag:uFEH+vVvlTAN03xCatkc2g==,type:str]
    version: 3.13.3
