apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - release.yaml
  - rclone-music-deployment.yaml
  - rclone-music-service.yaml
  - rclone-music-ingress.yaml
  - rclone-music-update.yaml
  - secrets/rclone-music.enc.yaml
  - secrets/ghcr-pull-secret.enc.yaml
