apiVersion: v1
kind: Service
metadata:
  name: oh-my-ytdl
  namespace: jellyfin
  labels:
    app.kubernetes.io/name: oh-my-ytdl
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: oh-my-ytdl
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
