---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-home-work
  namespace: adguard-home
  labels:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/component: work
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-homelab
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-home-conf
  namespace: adguard-home
  labels:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/component: config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-homelab
  resources:
    requests:
      storage: 1Gi
