apiVersion: v1
kind: Secret
metadata:
    name: konomitv-basic-auth
    namespace: jellyfin
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:wtsnyWuJX9I=,iv:1kz1lUN2TNAdjNGgbDkqVAKj0gwOitV+ZNFP+nJH+ig=,tag:a/htcK4bgusS2oqOcorHqQ==,type:str]
    password: ENC[AES256_GCM,data:PEuY65h/4AU=,iv:C2pMj++RpyL0TVjpwKiix/68fVTqzVLwwhigBhTUzb0=,tag:0z8ZRtc39ziVu5pAN/Jsyw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MFVleHcyc28xSEp4Z2lS
            Y05qVFlKZlovcFZkY2JNMGdrOElIeWdYY1VRClVQeUtxd1AyUnM1SEplakNVamd6
            RWd3b0hGMlRVNTg2UU5LVzBIWVd1K0kKLS0tIHRMZ1gzNzNoa0VCbEIzTXorY1gx
            RGtLa25zbGp4Yy9TcFAzSHhXWGlWZzgK63TijMAQsJ86D/CtFTsYHwqS7NeCeFLP
            ou9Rj92YfMxKK6ZRXmcSISZI8yRe/N6a7QsB75elTtOpbaGp0a/aJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T07:01:25Z"
    mac: ENC[AES256_GCM,data:QubOj1dsrngEwqr4nJkfWLs4ZHWDgF6UKnehIH0b9cZLV5A+6b5521+1jBcDvq7UKVe/+UGfD17ddlGIsMWGQKW0JkZ5Ylq8D0ttJXbwvQssW4tKSdfsEJ7xb067Pep2aJDmz/r5qjtPd16xGjmvYuP4g5fUBO+fk7gfQlmPVXM=,iv:wgbc3OZDqSgeGJR824gPM7LJjI3TfqPkIyORjS3fJ0o=,tag:IXOgJWCFNngVBGp3JM5CLA==,type:str]
    version: 3.13.1
