apiVersion: v1
kind: Secret
metadata:
    name: konomitv-basic-auth
    namespace: jellyfin
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:5WVWMjPtT7s=,iv:iGh0+HAelzcvHOC9dqO2HdwWkKYRCmW+DEPD7IkiCqw=,tag:HsLfNWh56gdG5kcbvNmSZw==,type:str]
    password: ENC[AES256_GCM,data:6qknILZYHJNmq+MWwpVL7YrgCRw=,iv:cOTQ/UOiAkmcVvrOtWCEgyM7KtimWr9iS+ZbuecYkUc=,tag:vK3xVi+gECjpbHTh/jj+ow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwaEVwRkIyUGpBenJYdG8v
            Q1RNQWh1ZmxjTVl0MkNSb3NKV1dIVWpFSlhFCmFtSzdzem4yUGR3Z3VSMzhxaHR5
            UXZzTHdJN3pBZys0YjdjdjFiUzUzYm8KLS0tIDRrcEl0UDVCdXhVLzRNWkozM0N6
            cDZmZlJ4MWFqdUJuZVZlOU5nbWJ2dEEKOI0XaUeAVs9mT1VIKSJowFYYaj4e67UE
            Z1P6Zz5uK3548rKu7DKzzPLq3VTI7LgIzpoYWNYGL0S8dD3nS1JufA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T05:38:22Z"
    mac: ENC[AES256_GCM,data:oDbS+rICaVwMNNqC0pfItcGTLjEMVol1SqgXLIxsfLrq8R3hU3Go37xCscgIFsfdYWc9/AblovsosVn2HTF5Z7RHCIJYQC1o+JScVAsmaMCnhSN1d9nG6V8Uu2y/OlJuboiTWoW8GoG356Us+wj5LL4xVcGgX9LjgaNlj6Uvtp4=,iv:9OqcUJupNzfBPSFqh0r137YGgcshhzdnSSjIcS+9jqo=,tag:DzeIR3u3kqhYGnBKxzV2Cw==,type:str]
    version: 3.13.1
