---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: codex
  namespace: codex
spec:
  hard:
    pods: "4"
    persistentvolumeclaims: "2"
    requests.cpu: "2"
    requests.memory: 5Gi
    requests.storage: 30Gi
    limits.cpu: "5"
    limits.memory: 8Gi
