apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: invidious

resources:
  - namespace.yaml
  - postgres.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - restart-cronjob.yaml
  - secrets/invidious-secrets.enc.yaml
  - update.yaml

configMapGenerator:
  - name: invidious-config
    files:
      - application.yml=config/application.yml
