---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: invidious
  namespace: invidious
spec:
  image: quay.io/invidious/invidious
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: invidious
  namespace: invidious
spec:
  imageRepositoryRef:
    name: invidious
  filterTags:
    pattern: '^latest$'
  policy:
    alphabetical:
      order: asc
  digestReflectionPolicy: Always
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: invidious-companion
  namespace: invidious
spec:
  image: quay.io/invidious/invidious-companion
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: invidious-companion
  namespace: invidious
spec:
  imageRepositoryRef:
    name: invidious-companion
  filterTags:
    pattern: '^latest$'
  policy:
    alphabetical:
      order: asc
  digestReflectionPolicy: Always
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: invidious
  namespace: invidious
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
    push:
      branch: main
  update:
    path: ./k8s/apps/base/invidious
    strategy: Setters
