apiVersion: v1
kind: Secret
metadata:
    name: invidious-secrets
    namespace: invidious
type: Opaque
stringData:
    hmac-key: ENC[AES256_GCM,data:IlV4T2+OnXkTpZEHqs27204zs+q9uHIZFSqKW/4D+MQCt7OZwbkPTA==,iv:XR6pOKHUp1VERsNk43teVsj4Es+nPDlVuGBeb8d8tB0=,tag:v3W47TUWzuVJt7MfY6NWWQ==,type:str]
    companion-key: ENC[AES256_GCM,data:ptIRNc5Img/Dt2uPeAe0wg==,iv:+jt0XXuwbqNFf5NX3PXOdCW9qWmVssxD0sBKBI9dbzI=,tag:n+Ces+qbI/5W+goRB3e1VA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRjdIaXBYNEJDTTc2RVFw
            UTJma1g4dTI0NExGczRYV3ZoT1dFWll2R3hzCjg3TzRaS2tlOVVRWXRqWHVVK1pM
            eHZFclVuMEJmL2JKVDlXRC92NDNrYlkKLS0tIG1COCtmenN2SXhibHoxTk5QMWRI
            Q3oxalFmME4yRjJRVndBamJ1VzUzdUUKPdj9PF3FHoXmbs7RUtpu7ccviyjpEb1j
            Q/Oxosy9b8jTep9OObUkWeAOOBXB4ZssCTp5DunKg/eqICBhEPFadg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T16:25:01Z"
    mac: ENC[AES256_GCM,data:/C7uv55WI9VS/mZz9jhfiHuCLoANeK6Sxrk0QIZgaKdEiyYfiGzEr2XJbpE8L0wnWImpFTHbt0l3sdE657w85qmfhwSEx3zlAjYdusTPEIgvTcApuScn9xntFINuRm85IJbSgcyoE27wopKWr1KQLBX+W0z1cGS+gCcwlb4DCp8=,iv:sAn5iR9FXPCXraObDeERT4c4ww+GaFjo3hDO9k7qfOU=,tag:0kYyj0DKudPf+/z8b607EQ==,type:str]
    version: 3.13.1
