---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: openclaw
  namespace: openclaw
spec:
  image: ghcr.io/openclaw/openclaw
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: openclaw
  namespace: openclaw
spec:
  imageRepositoryRef:
    name: openclaw
  filterTags:
    pattern: '^(?P<version>[0-9]+\.[0-9]+\.[0-9]+)$'
    extract: "$version"
  policy:
    semver:
      range: ">=2026.9.1 <2026.9.2"
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: grafana-cloud-mcp
  namespace: openclaw
spec:
  image: docker.io/grafana/mcp-grafana
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: grafana-cloud-mcp
  namespace: openclaw
spec:
  imageRepositoryRef:
    name: grafana-cloud-mcp
  filterTags:
    pattern: '^(?P<version>[0-9]+\.[0-9]+\.[0-9]+)$'
    extract: "$version"
  policy:
    semver:
      range: ">=0.0.0"
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: openclaw
  namespace: openclaw
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
    push:
      branch: main
  update:
    path: ./k8s/apps/base/openclaw
    strategy: Setters
