---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yattee-server-data
  namespace: yattee-server
  labels:
    app: yattee-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-homelab
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yattee-server-downloads
  namespace: yattee-server
  labels:
    app: yattee-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-homelab
  resources:
    requests:
      storage: 5Gi
