apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:6vE1YjQJxXCkppoNls55k2wu8sfHFQx9WLPnTlvwvCg3CfcLLowmKyhqwhD1KsiMZ1S9eP44qUHY+0UDlJubreowcKqJXfr0O3D6kfJa5zJRWQ==,iv:cVzIAzDVHsTrBexbjKfq3az4bf3GhYQ+nk7O2FwQa+o=,tag:CS7ESI39QtrQnu3x8sbTDA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNXV1RVdsdGhPYk1PV3dm
            a3NWTVhRempWYzkraE03c0x4YUo0SFNJYnpFCkxSa2FFTk9jY0ZnUWFZSnAzUDZC
            MHVTU1YwQU9sNlVMUDNLVnNvZEl5QjAKLS0tIFJGakJHWStBaCswZXowQ0Y2Q2Fz
            SjgxN25uc3lhVEtXTWJoektiTnhmUHcKRYPdCwM6wTrHT3ySimj/ydNS+zvVypqv
            jJAncrWcJkg3JNsdEtFytHyClu4LYKn2IWMbD6PNJXEq19aXW0X+uQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T07:35:02Z"
    mac: ENC[AES256_GCM,data:YsCWjLpZ7UtMZGfdK1rk/T+Sud1sKQMpDtsnFYgCiKd9h5LE5wMmN6+P5+b/CHyBJb2uRKl6iShcVQ0Q3eHrYlrzL5MBmpBZM0A0XK34Os71KMYt+ErU/oZiZMmQgxtWW1R3mdlxjWLAwGqX6SUUn3DpODQM99n1ZqLaT50ay0g=,iv:1N0QyX8BwLUm2Ihm5PuoSpXo4oiaS9iGLmbiVXZ5aPk=,tag:v9qVytPjx0k3t3iyogzEaw==,type:str]
    version: 3.13.1
