kind: Secret
apiVersion: v1
metadata:
    name: authentik-openshell-oidc
    namespace: authentik
data:
    OPENCLAW_OPENSHELL_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:xUQGbl/CvnfbeegXYG03M/PczzuSjr57JjO9PHtVsWx+uJ0vC8Qk4oyPSmq5NPHjjvUnhQ9tN/BAPKlZtdg5MbYBz38za/ye1KiuX1iXG6Vu7p5pcFKNTA==,iv:bdRuXaflmxDQyH5qL4REWY19I1HRB4QH11lT4TSFnO8=,tag:cHurEEi5eN+Qee1ra/bcEA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRHFQUFhwUTdINUU2elVv
            VWs2T2hUZ1Z6Y3k0WmcyaU84RC8xbFpna2c0CnNoQmRWZEdGb2tXSTlrcUIwTW1W
            VndrenJCcXo0UUJaRXFOaUpMelhveUUKLS0tIFZ5L3dBaFNaTDdTTTJ0MG5UZm9X
            UmhkZ0VIVzhLeVNGVStDUy9Rc2gxRVkKasd5kLmNusovmZNpf+y9lmkbhbASU8P2
            3Q9R+7AwP4s40Uk9IQtcZIcYwadyG+rjR3WpWT2UO2plVX1zlFlifA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T10:19:12Z"
    mac: ENC[AES256_GCM,data:+ucozaWp1QZoszidmYsTJbRpCzn1jGrVvDfCcwq7YrQd8aU9Www9km42T+JhJM6fR8H8DCi0haoWZLMwaMuKV9P10uAxtQyKc4Hk1QASUQCS/CbEtIS3JW8am5qQDNhsq6KC86lcde6/XPTUw7UX3GJ7OcMb7lVbWuMbJqS5PvA=,iv:UtSAAgaZ3GCsbdZvpNXBK9UX/RBl0Yz93Z2cdk+zsR0=,tag:VA303eE9pJp/CASGL2Qw/Q==,type:str]
    version: 3.13.1
