apiVersion: v1
kind: Secret
metadata:
    name: misskey-backup
    namespace: misskey
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:OVajaruC5eT4K8SPe2O6NOk59RejvGcQkwKH4/w8zYWS4pCfdl7591Z/EeqBiSD02/vds5VPSV0aG+MVbQ==,iv:FkRr+jvkNLJ4KQZqZqtQbumOg7kPfA882jumBkN1dtw=,tag:xxCU6ymJpZP0TkrvI8NuIw==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:XOW4KTzhSWNL0VxQGr/qYFlqv/3IBeTtQSICZX0GLBH2+sMykPJ8gw==,iv:jLbd1GA1w38cXRaOc7u//MEPrZ0QsbopidVUwQT+Fq0=,tag:wdT6uzLmW6UhLCOOpEjZ6A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ajhhVURzQ2FYbkgyeVdK
            RDhoV3o1SmRBTFdpNkJNOG96RGliaGR6R2lBCkN0ZEpocW9mRzgwU1lwV1dSc21z
            d3JmczhNR1FUc3hvZDlVa0UrcUloeG8KLS0tIEtNbENPVmxRa0w4TVpONVRqdk1H
            SHBvWjRyOVUxZ1VvbUloRVBJd0MvWVEKhVoPXNkGaRfZ3mcPgYLrZZLEvIY7L7ke
            thzlyTOmq/DckcwjvsOOxczyNrB0t5CzciBPm3WlqPZL+2l4VwGhKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T07:31:16Z"
    mac: ENC[AES256_GCM,data:/0/TP23D5iPIqfiMJ7aG8nAmywnRENLAGCD1uNi0qYzLoteEjozFw5+159+ice/AV2osIOiylWv+mmt0SbP65CCma/hJlhCJtO6S/tqIOcw5NA6gHqi1Q5k/MRuR/1Gbi8qU4fqxcl7h5XIcqaWzpA7vXNwNjrFqt5M3jC5x1ug=,iv:T3jq3sdvRJggYWlEPV3gNOL49V5K0scwA/G6Y/ZTI9M=,tag:ry7od3t6Ql4eougET6Ovig==,type:str]
    version: 3.13.1
