apiVersion: v1
kind: Secret
metadata:
    name: misskey-postgres
    namespace: misskey
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:30OlVmN/zA==,iv:KFkRUXTSuZ+/o64EQB83AhQidrlglSZLQ+tyXjzMQV8=,tag:/ISs4Z9Zgsv3sSs5OlHjGQ==,type:str]
    password: ENC[AES256_GCM,data:loCZSHg2btAexptmoWr3+ByQbxQ=,iv:rxviXGyt4+rFuxMmadtOV/5HEMJpORzW7wSTvgqp8mU=,tag:ufGjf/kn6Pwz6nRzfbj1IQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMFpzZzJBK0lHWjcwbGZL
            RVNXWUhhUHFnYTBOOUVldXViVm5TSlJudkFBCkpzSzlFU0ZsTFZKcmRtdGdldkJz
            SUVieklRZjM3S2xscFJWKzN4ZHk5aEkKLS0tIFJ5S2F6QjVoU2VZbWNYdmNkb3VZ
            VWV6TGxQaGhDVzZGbW5nV2RiOURlN2MK/vENGRvY1bLd5fURSZw/M6nZyPgZ9YhQ
            T/jQJgoM+JSYjwjbKCZ/CKqFx0lI0Jf/tuVwgv155hYVwDCp3UX46Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T07:36:36Z"
    mac: ENC[AES256_GCM,data:ymSHAUlhHYzN/0BFVt9/Zyvk4M3JJC7OACTNr4IMC/JpraOSDGLSfRY524haLx/aX+gnb2+SpJ/98K1P+mgIyEGo7r204fIA5GaspQRLmqX6Uy9V9Ncji6eFiS+MjDze8S/vSV9yGyAt834JeZbQEsTZ66nVEaiW/wjCytY2U6g=,iv:shjku5uk8rOYVFZoWKBsvpq1xHMwQWYtWY2R9MOLYB4=,tag:8G74dtxL5izwo3PnvCiYTQ==,type:str]
    version: 3.13.1
