apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ai
  namespace: ai
  labels:
    app: ai
spec:
  replicas: 0
  serviceName: ai
  selector:
    matchLabels:
      app: ai
  template:
    metadata:
      labels:
        app: ai
    spec:
      initContainers:
        - name: init-font-file
          image: docker.io/library/busybox:1.37.0
          command:
            - /bin/sh
            - -c
            - |
              mkdir -p /font
              touch /font/font.ttf
              wget -O /font/font.ttf https://github.com/coz-m/MPLUS_FONTS/raw/refs/heads/master/fonts/MPLUS1/ttf/MPLUS1-Regular.ttf
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
            - name: font-file
              mountPath: /font
      containers:
        - name: ai
          image: ghcr.io/kentaro1043/ai-arm64:latest@sha256:d24bd6bdf47e0e717b5a38f2b37c8ed7dc209f869a1e5cb12cacc682a5615aef
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 20m
              memory: 256Mi
          volumeMounts:
            - name: data
              mountPath: /ai/data
            - name: config-json
              mountPath: /ai/config.json
              readOnly: true
              subPath: config.json
            - name: font-file
              mountPath: /ai/font.ttf
              readOnly: true
              subPath: font.ttf
      volumes:
        - name: config-json
          secret:
            secretName: ai-config-json
        - name: font-file
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: nfs-homelab
        resources:
          requests:
            storage: 100Mi
