apiVersion: v1
kind: Secret
metadata:
    name: rclone-music
    namespace: jellyfin
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:s9ZGAYlB,iv:x1Bxyr2nptN+ezSgV3/LHSeO6wLWscizVZZIjFul3Cw=,tag:pjNaxnR+vUtuYWGs7tjYEw==,type:str]
    password: ENC[AES256_GCM,data:gAO6ECoQaqKpNtB1L9wVLWYMN2A=,iv:PrkT03E1rmqmLf85MujdveQ4kIopewVglguor4AlUF8=,tag:dqt08bJ5i34hleK53pvBLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLN0kxNmVhTzV0ZjFKcy94
            Yk5YSEZjdDUzMXA4K2w5ZU5oQTNqRGZHS2kwCmtqa3dnWGh2aG50T0hGUlFzTzhM
            VVhDcUpTWnJlV3NoaGVIdytYc1VJYWsKLS0tIGRYM0N0R21odVRDMmNydmM0QVVw
            RVdYczF6MG8zSTB2ZHVpNzhZb0dDMWMK0IL6NKEOSIIyFXzwYSMWiOAISMr6uEbv
            NvM8gmNd3jASM+9TyP4eSQ/SFVtDnD3ynde6h8/DonYes6BnscaUlw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T12:52:53Z"
    mac: ENC[AES256_GCM,data:RzmaNGyk4B74xXMs36l2ZvaOy3ZF/aliTJftUK3HeCAaPIm2ucf0c21DZLtAjz+eByfj6icqheW31htMT/0jiP3XkmwdOPn4XTp3/HmGA4LwQADH44AfO/Pe4SEfD48zm1uYt6z+JxweO854Fabu7ohz5m814/hblSzHxT0GrsA=,iv:hJGdohBRLjSdHpyMuXQ8BmcG5ArXr+6DmgtFTwbBmPE=,tag:pUpKYxH9xd9DBdDgJao4nw==,type:str]
    version: 3.13.1
