apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: palworld-saved
  namespace: palworld
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-homelab
  resources:
    requests:
      storage: 5Gi
