apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: generic-device-plugin
  namespace: kube-system
  labels:
    app.kubernetes.io/name: generic-device-plugin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: generic-device-plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: generic-device-plugin
    spec:
      automountServiceAccountToken: false
      priorityClassName: system-node-critical
      containers:
        - name: generic-device-plugin
          image: ghcr.io/squat/generic-device-plugin:d660d1f
          imagePullPolicy: IfNotPresent
          args:
            - --domain=devices.kentaro1043.com
            - --device
            - |
              name: render
              groups:
                - paths:
                    - path: /dev/dri/renderD128
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 50m
              memory: 20Mi
          volumeMounts:
            - name: device-plugins
              mountPath: /var/lib/kubelet/device-plugins
            - name: dri
              mountPath: /dev/dri
              readOnly: true
      volumes:
        - name: device-plugins
          hostPath:
            path: /var/lib/kubelet/device-plugins
            type: Directory
        - name: dri
          hostPath:
            path: /dev/dri
            type: Directory
      tolerations:
        - operator: Exists
          effect: NoExecute
        - operator: Exists
          effect: NoSchedule
      terminationGracePeriodSeconds: 10
  updateStrategy:
    type: RollingUpdate
