apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cloudflare-tunnel-ingress-controller.yaml
  - secrets/cloudflare-credentials.enc.yaml

  - cert-manager.yaml

  - cloudnative-pg.yaml

  - mariadb-operator.yaml

  - csi-driver-nfs.yaml

  - traefik.yaml

  - local-path.yaml

  - generic-device-plugin.yaml
