---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 24h
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  interval: 12h
  chart:
    spec:
      chart: traefik
      version: "41.x"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
  values:
    deployment:
      kind: DaemonSet
    ingressClass:
      enabled: true
      isDefaultClass: true
      name: traefik
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.internal.kentaro1043.com`)
        entryPoints:
          - websecure
        tls:
          secretName: traefik-dashboard-tls
    updateStrategy:
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 0
